### ISSUE TITLE
the link for script run_sharedtask_eval.sh is corrupted

### ISSUE THREAD

**Issue by StalVars** [IBM/multidoc2dial#9]
Hi, I can't access the [run_sharedtask_eval.sh](https://github.com/IBM/multidoc2dial/blob/main/sharedtask/scripts/run_sharedtask_eval.sh) . It gives 404 error. Could you please check.
Thanks

**Comment by songfeng** [comment]
So sorry about it! Fixed in that README. It should be [`here`.](https://github.com/IBM/multidoc2dial/blob/main/scripts/run_sharedtask_eval.sh) 

Thanks,
Song
